[#ftl]
[#import "/spring.ftl" as spring]
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>Rekapitulace registrace</title>
    <link rel="stylesheet" href="/css/style.css"/>
</head>
<body>
<div class="container">
           <div class="registrace">
            <h1>Rekapitulace registrace</h1>
            <div>Registrace byla uspesna.</div>
        </div>
 </div>
</body>
</html>
